version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(go)"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/internal/web/frontend"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(npm)"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(actions)"